/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#e7eeff",
        "on-secondary-fixed-variant": "#93000b",
        "outline-variant": "#c2c7d1",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "tertiary-fixed-dim": "#ffb780",
        "on-tertiary-container": "#f9a767",
        background: "#f9f9ff",
        surface: "#FFFFFF",
        "on-primary": "#ffffff",
        "primary-container": "#0f4c81",
        tertiary: "#532800",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d8e3fb",
        "secondary-fixed": "#ffdad6",
        "tertiary-container": "#743b00",
        "surface-container-low": "#f0f3ff",
        "error-vibrant": "#F73333",
        "primary-fixed": "#d2e4ff",
        "inverse-surface": "#263143",
        "on-tertiary-fixed": "#2f1400",
        "on-error-container": "#93000a",
        "ink-base": "#0F172A",
        "surface-variant": "#d8e3fb",
        "secondary-fixed-dim": "#ffb4ab",
        secondary: "#bb0112",
        "surface-dim": "#cfdaf2",
        "secondary-container": "#e02928",
        "surface-bright": "#f9f9ff",
        "on-primary-container": "#8ebdf9",
        "on-tertiary-fixed-variant": "#6f3800",
        "inverse-primary": "#a0c9ff",
        "on-tertiary": "#ffffff",
        primary: "#00355f",
        "on-surface": "#111c2d",
        "on-background": "#111c2d",
        "on-primary-fixed-variant": "#07497d",
        "tertiary-fixed": "#ffdcc4",
        "error-container": "#ffdad6",
        "on-secondary-container": "#fffbff",
        outline: "#727780",
        "on-primary-fixed": "#001c37",
        error: "#ba1a1a",
        "background-subtle": "#F8FAFC",
        "surface-container-high": "#dee8ff",
        "primary-fixed-dim": "#a0c9ff",
        "on-secondary-fixed": "#410002",
        "surface-tint": "#2d6197",
        "on-surface-variant": "#42474f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-margin": "20px",
        "stack-lg": "24px",
        "stack-md": "16px",
        gutter: "16px",
        "component-height-md": "48px",
        "component-height-lg": "56px",
        "stack-sm": "8px",
        safe: "env(safe-area-inset-bottom)",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-lg": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
